# Preload Wallpapers
preload = /home/wrp/wallpaper/georges-boutros-pYFue5PzpcI-unsplash.jpg

# Set Wallpapers
wallpaper = ,/home/wrp/wallpaper/georges-boutros-pYFue5PzpcI-unsplash.jpg

# Disable Splash
splash = false
