# Preload Wallpapers
preload = /home/wrp/wallpaper/karsten-wurth-IMU55XrxS4E-unsplash.jpg

# Set Wallpapers
wallpaper = ,/home/wrp/wallpaper/karsten-wurth-IMU55XrxS4E-unsplash.jpg

# Disable Splash
splash = false
