# Preload Wallpapers
preload = /home/wrp/wallpaper/vista-do-ceu-noturno-estrelado-com-natureza-e-paisagem-montanhosa.jpg

# Set Wallpapers
wallpaper = ,/home/wrp/wallpaper/vista-do-ceu-noturno-estrelado-com-natureza-e-paisagem-montanhosa.jpg

# Disable Splash
splash = false
